### ISSUE TITLE
devtools throw out error

### ISSUE THREAD

**Issue by rainyear** [DASpringate/Rkoans#1]
![qq20131014-11 2x](https://f.cloud.github.com/assets/3953966/1323404/0140a5cc-347e-11e3-9df1-650b69ad0054.png)
cannot study_koans,
load_all(".") throw out errors:

Error in parse(text = lines, n = -1, srcfile = srcfile, keep.source = TRUE) : 
      unused argument(s) (keep.source = TRUE)

**Comment by DASpringate** [comment]
Hi, I've just tested this on windows and Linux and am unable to reproduce your error. It looks like you may have had a problem with the cloned repo.  Can you try cloning the repo again then cd into it and try again?  Also can you check that the study_koans() function is in R/koan_reader.R.  Which OS are you running on?

**Comment by rainyear** [comment]
I run debian on a virtualbox and use R version 2.15.1 (2012-06-22), and it still throws the same error. Then I install R version 3.0.2 (2013-09-25) on Mac OS, it works finally...
